<#import "parts/common.ftlh" as c>

<@c.page>
    <div style="text-align: center;">УНИВЕРСИТЕТ</div>
    <p></p>

    <table align="center">
        <thead>
        <tr>
            <th width="10%"><a href="/add/addStudents">Студенты</a></th>
            <th width="10%"><a href="/add/addCourses">Курсы</a></th>
            <th width="10%"><a href="/add/addProfessors">Профессора</a></th>
        </tr>
        </thead>
    </table>

</@c.page>